### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/ttt2-super-soda#8]
Recently this addon started to throw a script error if someone picked up a soda and then died.
Using the Steam Workshop version and newest TTT2 Base version from the Steam Workshop.
(I think this is the cause, noticed it after dying?)

Error:
```
[[TTT2] Super Soda [FEATURE]] gamemodes/terrortown/entities/entities/soda_shootup/shared.lua:97: attempt to index field 'Primary' (a nil value)
  1. func - gamemodes/terrortown/entities/entities/soda_shootup/shared.lua:97
   2. unknown - lua/includes/extensions/net.lua:38
```

**Comment by TimGoll** [comment]
Do you know which weapon was used here? It seems to not have the `Primary.Delay` variable. Which is a bug in that addon. I can try to check for this, but then supersoda still won't work for this addon

**Comment by mexikoedi** [comment]
> Do you know which weapon was used here? It seems to not have the `Primary.Delay` variable. Which is a bug in that addon. I can try to check for this, but then supersoda still won't work for this addon

Ah, ok good to know.
Sadly I don't know, I think it was a normal weapon and not an item from the shop.
This collection was used: https://steamcommunity.com/sharedfiles/filedetails/?id=1822673195
Used weapon packs in the collection are: "TTT Weapons", "Lykrast's TTT Weapon Collection", "TTT M9K Weapons".

**Comment by mexikoedi** [comment]
I think it would be a good idea to implement a check for Primary.Delay.
It works for most weapons and only a handful of weapons cause this error.
It's better if shootup doesn't work for these weapons instead of an error in the console.

Otherwise maybe set a default value for Primary.Delay if it doesn't exist.
